title: Creative Incubator
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.5649571
  brandStrength: 0.6911923
  lightness: 0.1251342
  brandColors:
    - '#FFFFFF'
    - '#030303'
    - '#1F62CE'
    - '#8910FF'
    - '#F0FF1D'
  rhythmicContrast: 0.4702003
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
name: Marcus Love Chiang
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.9913896033540368
layout_spectrum: 1
